REM Copyright 2008 Sahab Yazdani
REM 
REM Licensed under the Apache License, Version 2.0 (the "License");
REM you may not use this file except in compliance with the License.
REM You may obtain a copy of the License at
REM 
REM    http://www.apache.org/licenses/LICENSE-2.0
REM 
REM Unless required by applicable law or agreed to in writing, software
REM distributed under the License is distributed on an "AS IS" BASIS,
REM WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
REM See the License for the specific language governing permissions and
REM limitations under the License.

@echo off
jar cfvm Painterly.jar manifest.txt Document$SobelVector.class
jar ufv Painterly.jar Document.class
jar ufv Painterly.jar EntryPoint$1.class
jar ufv Painterly.jar EntryPoint.class
jar ufv Painterly.jar PainterlyFrame$1.class
jar ufv Painterly.jar PainterlyFrame$10.class
jar ufv Painterly.jar PainterlyFrame$11.class
jar ufv Painterly.jar PainterlyFrame$12.class
jar ufv Painterly.jar PainterlyFrame$13.class
jar ufv Painterly.jar PainterlyFrame$14.class
jar ufv Painterly.jar PainterlyFrame$15.class
jar ufv Painterly.jar PainterlyFrame$16.class
jar ufv Painterly.jar PainterlyFrame$17.class
jar ufv Painterly.jar PainterlyFrame$18.class
jar ufv Painterly.jar PainterlyFrame$19.class
jar ufv Painterly.jar PainterlyFrame$2.class
jar ufv Painterly.jar PainterlyFrame$20.class
jar ufv Painterly.jar PainterlyFrame$21.class
jar ufv Painterly.jar PainterlyFrame$3.class
jar ufv Painterly.jar PainterlyFrame$4.class
jar ufv Painterly.jar PainterlyFrame$5.class
jar ufv Painterly.jar PainterlyFrame$6.class
jar ufv Painterly.jar PainterlyFrame$7.class
jar ufv Painterly.jar PainterlyFrame$8.class
jar ufv Painterly.jar PainterlyFrame$9.class
jar ufv Painterly.jar PainterlyFrame.class
jar ufv Painterly.jar PainterlyPanel$1.class
jar ufv Painterly.jar PainterlyPanel.class
jar ufv Painterly.jar PainterlyStyle.class
jar ufv Painterly.jar StateChangeListener.class
jar ufv Painterly.jar VerticalTextIcon.class
jar ufv Painterly.jar com\jhlabs\composite\AddComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\AddComposite.class
jar ufv Painterly.jar com\jhlabs\composite\AverageComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\AverageComposite.class
jar ufv Painterly.jar com\jhlabs\composite\BurnComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\BurnComposite.class
jar ufv Painterly.jar com\jhlabs\composite\ColorBurnComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\ColorBurnComposite.class
jar ufv Painterly.jar com\jhlabs\composite\ColorComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\ColorComposite.class
jar ufv Painterly.jar com\jhlabs\composite\ColorDodgeComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\ColorDodgeComposite.class
jar ufv Painterly.jar com\jhlabs\composite\ContourComposite.class
jar ufv Painterly.jar com\jhlabs\composite\ContourCompositeContext.class
jar ufv Painterly.jar com\jhlabs\composite\DarkenComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\DarkenComposite.class
jar ufv Painterly.jar com\jhlabs\composite\DifferenceComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\DifferenceComposite.class
jar ufv Painterly.jar com\jhlabs\composite\DodgeComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\DodgeComposite.class
jar ufv Painterly.jar com\jhlabs\composite\ExclusionComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\ExclusionComposite.class
jar ufv Painterly.jar com\jhlabs\composite\HardLightComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\HardLightComposite.class
jar ufv Painterly.jar com\jhlabs\composite\HueComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\HueComposite.class
jar ufv Painterly.jar com\jhlabs\composite\LightenComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\LightenComposite.class
jar ufv Painterly.jar com\jhlabs\composite\MiscComposite.class
jar ufv Painterly.jar com\jhlabs\composite\MiscCompositeContext.class
jar ufv Painterly.jar com\jhlabs\composite\MultiplyComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\MultiplyComposite.class
jar ufv Painterly.jar com\jhlabs\composite\NegationComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\NegationComposite.class
jar ufv Painterly.jar com\jhlabs\composite\OverlayComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\OverlayComposite.class
jar ufv Painterly.jar com\jhlabs\composite\PinLightComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\PinLightComposite.class
jar ufv Painterly.jar com\jhlabs\composite\RGBComposite$RGBCompositeContext.class
jar ufv Painterly.jar com\jhlabs\composite\RGBComposite.class
jar ufv Painterly.jar com\jhlabs\composite\SaturationComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\SaturationComposite.class
jar ufv Painterly.jar com\jhlabs\composite\ScreenComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\ScreenComposite.class
jar ufv Painterly.jar com\jhlabs\composite\SoftLightComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\SoftLightComposite.class
jar ufv Painterly.jar com\jhlabs\composite\SubtractComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\SubtractComposite.class
jar ufv Painterly.jar com\jhlabs\composite\ValueComposite$Context.class
jar ufv Painterly.jar com\jhlabs\composite\ValueComposite.class
jar ufv Painterly.jar com\jhlabs\image\AbstractBufferedImageOp.class
jar ufv Painterly.jar com\jhlabs\image\ApplyMaskFilter.class
jar ufv Painterly.jar com\jhlabs\image\ArrayColormap.class
jar ufv Painterly.jar com\jhlabs\image\AverageFilter.class
jar ufv Painterly.jar com\jhlabs\image\BicubicScaleFilter.class
jar ufv Painterly.jar com\jhlabs\image\BinaryFilter.class
jar ufv Painterly.jar com\jhlabs\image\BlockFilter.class
jar ufv Painterly.jar com\jhlabs\image\BlurFilter.class
jar ufv Painterly.jar com\jhlabs\image\BorderFilter.class
jar ufv Painterly.jar com\jhlabs\image\BoxBlurFilter.class
jar ufv Painterly.jar com\jhlabs\image\BrushedMetalFilter.class
jar ufv Painterly.jar com\jhlabs\image\BumpFilter.class
jar ufv Painterly.jar com\jhlabs\image\CausticsFilter.class
jar ufv Painterly.jar com\jhlabs\image\CellularFilter$Point.class
jar ufv Painterly.jar com\jhlabs\image\CellularFilter.class
jar ufv Painterly.jar com\jhlabs\image\ChannelMixFilter.class
jar ufv Painterly.jar com\jhlabs\image\CheckFilter.class
jar ufv Painterly.jar com\jhlabs\image\ChromaKeyFilter.class
jar ufv Painterly.jar com\jhlabs\image\ChromeFilter$1.class
jar ufv Painterly.jar com\jhlabs\image\ChromeFilter.class
jar ufv Painterly.jar com\jhlabs\image\CircleFilter.class
jar ufv Painterly.jar com\jhlabs\image\Colormap.class
jar ufv Painterly.jar com\jhlabs\image\CompositeFilter.class
jar ufv Painterly.jar com\jhlabs\image\CompoundFilter.class
jar ufv Painterly.jar com\jhlabs\image\ContourFilter.class
jar ufv Painterly.jar com\jhlabs\image\ContrastFilter.class
jar ufv Painterly.jar com\jhlabs\image\ConvolveFilter.class
jar ufv Painterly.jar com\jhlabs\image\CropFilter.class
jar ufv Painterly.jar com\jhlabs\image\CrystallizeFilter.class
jar ufv Painterly.jar com\jhlabs\image\CurlFilter$Sampler.class
jar ufv Painterly.jar com\jhlabs\image\CurlFilter.class
jar ufv Painterly.jar com\jhlabs\image\CurvesFilter$Curve.class
jar ufv Painterly.jar com\jhlabs\image\CurvesFilter.class
jar ufv Painterly.jar com\jhlabs\image\DespeckleFilter.class
jar ufv Painterly.jar com\jhlabs\image\DiffuseFilter.class
jar ufv Painterly.jar com\jhlabs\image\DiffusionFilter.class
jar ufv Painterly.jar com\jhlabs\image\DilateFilter.class
jar ufv Painterly.jar com\jhlabs\image\DisplaceFilter.class
jar ufv Painterly.jar com\jhlabs\image\DissolveFilter.class
jar ufv Painterly.jar com\jhlabs\image\DitherFilter.class
jar ufv Painterly.jar com\jhlabs\image\EdgeFilter.class
jar ufv Painterly.jar com\jhlabs\image\EmbossFilter.class
jar ufv Painterly.jar com\jhlabs\image\EqualizeFilter.class
jar ufv Painterly.jar com\jhlabs\image\ErodeAlphaFilter.class
jar ufv Painterly.jar com\jhlabs\image\ErodeFilter.class
jar ufv Painterly.jar com\jhlabs\image\ExposureFilter.class
jar ufv Painterly.jar com\jhlabs\image\FadeFilter.class
jar ufv Painterly.jar com\jhlabs\image\FBMFilter.class
jar ufv Painterly.jar com\jhlabs\image\FeedbackFilter.class
jar ufv Painterly.jar com\jhlabs\image\FieldWarpFilter$Line.class
jar ufv Painterly.jar com\jhlabs\image\FieldWarpFilter.class
jar ufv Painterly.jar com\jhlabs\image\FillFilter.class
jar ufv Painterly.jar com\jhlabs\image\FlareFilter.class
jar ufv Painterly.jar com\jhlabs\image\FlipFilter.class
jar ufv Painterly.jar com\jhlabs\image\Flush3DFilter.class
jar ufv Painterly.jar com\jhlabs\image\FourColorFilter.class
jar ufv Painterly.jar com\jhlabs\image\GainFilter.class
jar ufv Painterly.jar com\jhlabs\image\GammaFilter.class
jar ufv Painterly.jar com\jhlabs\image\GaussianFilter.class
jar ufv Painterly.jar com\jhlabs\image\GlintFilter.class
jar ufv Painterly.jar com\jhlabs\image\GlowFilter.class
jar ufv Painterly.jar com\jhlabs\image\Gradient.class
jar ufv Painterly.jar com\jhlabs\image\GradientFilter.class
jar ufv Painterly.jar com\jhlabs\image\GradientWipeFilter.class
jar ufv Painterly.jar com\jhlabs\image\GrayFilter.class
jar ufv Painterly.jar com\jhlabs\image\GrayscaleColormap.class
jar ufv Painterly.jar com\jhlabs\image\GrayscaleFilter.class
jar ufv Painterly.jar com\jhlabs\image\HalftoneFilter.class
jar ufv Painterly.jar com\jhlabs\image\Histogram.class
jar ufv Painterly.jar com\jhlabs\image\HSBAdjustFilter.class
jar ufv Painterly.jar com\jhlabs\image\ImageCombiningFilter.class
jar ufv Painterly.jar com\jhlabs\image\ImageMath.class
jar ufv Painterly.jar com\jhlabs\image\ImageUtils.class
jar ufv Painterly.jar com\jhlabs\image\InterpolateFilter.class
jar ufv Painterly.jar com\jhlabs\image\InvertAlphaFilter.class
jar ufv Painterly.jar com\jhlabs\image\InvertFilter.class
jar ufv Painterly.jar com\jhlabs\image\IteratedFilter.class
jar ufv Painterly.jar com\jhlabs\image\JavaLnFFilter.class
jar ufv Painterly.jar com\jhlabs\image\KaleidoscopeFilter.class
jar ufv Painterly.jar com\jhlabs\image\KeyFilter.class
jar ufv Painterly.jar com\jhlabs\image\LensBlurFilter.class
jar ufv Painterly.jar com\jhlabs\image\LevelsFilter.class
jar ufv Painterly.jar com\jhlabs\image\LifeFilter.class
jar ufv Painterly.jar com\jhlabs\image\LightFilter$1.class
jar ufv Painterly.jar com\jhlabs\image\LightFilter$AmbientLight.class
jar ufv Painterly.jar com\jhlabs\image\LightFilter$DistantLight.class
jar ufv Painterly.jar com\jhlabs\image\LightFilter$Light.class
jar ufv Painterly.jar com\jhlabs\image\LightFilter$Material.class
jar ufv Painterly.jar com\jhlabs\image\LightFilter$PointLight.class
jar ufv Painterly.jar com\jhlabs\image\LightFilter$SpotLight.class
jar ufv Painterly.jar com\jhlabs\image\LightFilter.class
jar ufv Painterly.jar com\jhlabs\image\LinearColormap.class
jar ufv Painterly.jar com\jhlabs\image\LookupFilter.class
jar ufv Painterly.jar com\jhlabs\image\MapColorsFilter.class
jar ufv Painterly.jar com\jhlabs\image\MapFilter.class
jar ufv Painterly.jar com\jhlabs\image\MarbleFilter.class
jar ufv Painterly.jar com\jhlabs\image\MarbleTexFilter.class
jar ufv Painterly.jar com\jhlabs\image\MaskFilter.class
jar ufv Painterly.jar com\jhlabs\image\MaximumFilter.class
jar ufv Painterly.jar com\jhlabs\image\MedianFilter.class
jar ufv Painterly.jar com\jhlabs\image\MinimumFilter.class
jar ufv Painterly.jar com\jhlabs\image\MirrorFilter.class
jar ufv Painterly.jar com\jhlabs\image\MotionBlurFilter.class
jar ufv Painterly.jar com\jhlabs\image\MotionBlurOp.class
jar ufv Painterly.jar com\jhlabs\image\MutatableFilter.class
jar ufv Painterly.jar com\jhlabs\image\NoiseFilter.class
jar ufv Painterly.jar com\jhlabs\image\OctTreeQuantizer$OctTreeNode.class
jar ufv Painterly.jar com\jhlabs\image\OctTreeQuantizer.class
jar ufv Painterly.jar com\jhlabs\image\OffsetFilter.class
jar ufv Painterly.jar com\jhlabs\image\OilFilter.class
jar ufv Painterly.jar com\jhlabs\image\OpacityFilter.class
jar ufv Painterly.jar com\jhlabs\image\OutlineFilter.class
jar ufv Painterly.jar com\jhlabs\image\PerspectiveFilter.class
jar ufv Painterly.jar com\jhlabs\image\PinchFilter.class
jar ufv Painterly.jar com\jhlabs\image\PixelUtils.class
jar ufv Painterly.jar com\jhlabs\image\PlasmaFilter.class
jar ufv Painterly.jar com\jhlabs\image\PointFilter.class
jar ufv Painterly.jar com\jhlabs\image\PointillizeFilter.class
jar ufv Painterly.jar com\jhlabs\image\PolarFilter.class
jar ufv Painterly.jar com\jhlabs\image\PosterizeFilter.class
jar ufv Painterly.jar com\jhlabs\image\PremultiplyFilter.class
jar ufv Painterly.jar com\jhlabs\image\QuantizeFilter.class
jar ufv Painterly.jar com\jhlabs\image\Quantizer.class
jar ufv Painterly.jar com\jhlabs\image\QuiltFilter.class
jar ufv Painterly.jar com\jhlabs\image\RaysFilter.class
jar ufv Painterly.jar com\jhlabs\image\ReduceNoiseFilter.class
jar ufv Painterly.jar com\jhlabs\image\RenderTextFilter.class
jar ufv Painterly.jar com\jhlabs\image\RescaleFilter.class
jar ufv Painterly.jar com\jhlabs\image\RGBAdjustFilter.class
jar ufv Painterly.jar com\jhlabs\image\RippleFilter.class
jar ufv Painterly.jar com\jhlabs\image\RotateFilter.class
jar ufv Painterly.jar com\jhlabs\image\SaturationFilter.class
jar ufv Painterly.jar com\jhlabs\image\ScaleFilter.class
jar ufv Painterly.jar com\jhlabs\image\ScratchFilter.class
jar ufv Painterly.jar com\jhlabs\image\ShadeFilter.class
jar ufv Painterly.jar com\jhlabs\image\ShadowFilter.class
jar ufv Painterly.jar com\jhlabs\image\ShapeFilter.class
jar ufv Painterly.jar com\jhlabs\image\SharpenFilter.class
jar ufv Painterly.jar com\jhlabs\image\ShatterFilter$Tile.class
jar ufv Painterly.jar com\jhlabs\image\ShatterFilter.class
jar ufv Painterly.jar com\jhlabs\image\ShearFilter.class
jar ufv Painterly.jar com\jhlabs\image\ShineFilter.class
jar ufv Painterly.jar com\jhlabs\image\SkeletonFilter.class
jar ufv Painterly.jar com\jhlabs\image\SkyFilter.class
jar ufv Painterly.jar com\jhlabs\image\SmartBlurFilter.class
jar ufv Painterly.jar com\jhlabs\image\SmearFilter.class
jar ufv Painterly.jar com\jhlabs\image\SolarizeFilter.class
jar ufv Painterly.jar com\jhlabs\image\SparkleFilter.class
jar ufv Painterly.jar com\jhlabs\image\Spectrum.class
jar ufv Painterly.jar com\jhlabs\image\SpectrumColormap.class
jar ufv Painterly.jar com\jhlabs\image\SphereFilter.class
jar ufv Painterly.jar com\jhlabs\image\SplineColormap.class
jar ufv Painterly.jar com\jhlabs\image\StampFilter.class
jar ufv Painterly.jar com\jhlabs\image\SwimFilter.class
jar ufv Painterly.jar com\jhlabs\image\TextureFilter.class
jar ufv Painterly.jar com\jhlabs\image\ThresholdFilter.class
jar ufv Painterly.jar com\jhlabs\image\TileImageFilter.class
jar ufv Painterly.jar com\jhlabs\image\TransferFilter.class
jar ufv Painterly.jar com\jhlabs\image\TransformFilter.class
jar ufv Painterly.jar com\jhlabs\image\TransitionFilter.class
jar ufv Painterly.jar com\jhlabs\image\TwirlFilter.class
jar ufv Painterly.jar com\jhlabs\image\UnpremultiplyFilter.class
jar ufv Painterly.jar com\jhlabs\image\UnsharpFilter.class
jar ufv Painterly.jar com\jhlabs\image\VariableBlurFilter.class
jar ufv Painterly.jar com\jhlabs\image\WarpFilter.class
jar ufv Painterly.jar com\jhlabs\image\WarpGrid.class
jar ufv Painterly.jar com\jhlabs\image\WaterFilter.class
jar ufv Painterly.jar com\jhlabs\image\WeaveFilter.class
jar ufv Painterly.jar com\jhlabs\image\WholeImageFilter.class
jar ufv Painterly.jar com\jhlabs\image\WoodFilter.class
jar ufv Painterly.jar com\jhlabs\math\BinaryFunction.class
jar ufv Painterly.jar com\jhlabs\math\BlackFunction.class
jar ufv Painterly.jar com\jhlabs\math\CellularFunction2D$Point.class
jar ufv Painterly.jar com\jhlabs\math\CellularFunction2D.class
jar ufv Painterly.jar com\jhlabs\math\CompositeFunction1D.class
jar ufv Painterly.jar com\jhlabs\math\CompoundFunction2D.class
jar ufv Painterly.jar com\jhlabs\math\FBM.class
jar ufv Painterly.jar com\jhlabs\math\FFT.class
jar ufv Painterly.jar com\jhlabs\math\FractalSumFunction.class
jar ufv Painterly.jar com\jhlabs\math\Function1D.class
jar ufv Painterly.jar com\jhlabs\math\Function2D.class
jar ufv Painterly.jar com\jhlabs\math\Function3D.class
jar ufv Painterly.jar com\jhlabs\math\ImageFunction2D.class
jar ufv Painterly.jar com\jhlabs\math\MarbleFunction.class
jar ufv Painterly.jar com\jhlabs\math\MathFunction1D.class
jar ufv Painterly.jar com\jhlabs\math\Noise.class
jar ufv Painterly.jar com\jhlabs\math\RidgedFBM.class
jar ufv Painterly.jar com\jhlabs\math\SCNoise.class
jar ufv Painterly.jar com\jhlabs\math\TurbulenceFunction.class
jar ufv Painterly.jar com\jhlabs\math\VLNoise.class
jar ufv Painterly.jar com\jhlabs\vecmath\AxisAngle4f.class
jar ufv Painterly.jar com\jhlabs\vecmath\Color4f.class
jar ufv Painterly.jar com\jhlabs\vecmath\Matrix4f.class
jar ufv Painterly.jar com\jhlabs\vecmath\Point3f.class
jar ufv Painterly.jar com\jhlabs\vecmath\Point4f.class
jar ufv Painterly.jar com\jhlabs\vecmath\Quat4f.class
jar ufv Painterly.jar com\jhlabs\vecmath\Tuple3f.class
jar ufv Painterly.jar com\jhlabs\vecmath\Tuple4f.class
jar ufv Painterly.jar com\jhlabs\vecmath\Vector3f.class
jar ufv Painterly.jar com\jhlabs\vecmath\Vector4f.class
